# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set work directory
WORKDIR /code

# Install dependencies
COPY ./backend/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy the backend directory contents into the container at /code
COPY ./backend /code

# Command to run the application
CMD ['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '8000']
